# Generated by Django 3.1 on 2020-08-09 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20200810_0440'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content2',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='content3',
            field=models.TextField(null=True),
        ),
    ]
