# Generated by Django 3.1 on 2020-08-09 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20200810_0509'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='content2',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='content',
            field=models.TextField(null=True),
        ),
    ]
