# Generated by Django 3.1 on 2020-08-10 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_post2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content2',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='content3',
            new_name='remaining',
        ),
        migrations.AddField(
            model_name='post',
            name='gender',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
